wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day00.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day01.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day02.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day03.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day04.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day05.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day06.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day07.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day08.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day09.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day10.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day11.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day12.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day13.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day14.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day15.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day16.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day17.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day18.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day19.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day20.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day21.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day22.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day23.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day24.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day25.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day26.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day27.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day28.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day29.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day30.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day31.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day32.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day33.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day34.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day35.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day36.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day37.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day38.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day39.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day40.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day41.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day42.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day43.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day44.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day45.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day46.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day47.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day48.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day49.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day50.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day51.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day52.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day53.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_day54.joblib &
wget -P dataset_2nd/predict_5_days http://homepage.ntu.edu.tw/~jiada/ESUN/dataset_2nd/predict_5_days/db_pred.joblib &
wait