name: ESUN2
channels:
  - conda-forge
  - anaconda
dependencies:
  - python=3.10
  - cudatoolkit=11.6
  - joblib
  - ipython
  - jupyterlab
  - notebook
  - catboost=1.2.2
  - pandas
  - xlrd
  - openpyxl
  - odfpy
  - tqdm